//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpAccounting.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EpAccounting.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnung.doc.
        /// </summary>
        public static string BillFileName {
            get {
                return ResourceManager.GetString("BillFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen.
        /// </summary>
        public static string Command_DisplayName_Add {
            get {
                return ResourceManager.GetString("Command_DisplayName_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string Command_DisplayName_Cancel {
            get {
                return ResourceManager.GetString("Command_DisplayName_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellen.
        /// </summary>
        public static string Command_DisplayName_Create {
            get {
                return ResourceManager.GetString("Command_DisplayName_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string Command_DisplayName_Delete {
            get {
                return ResourceManager.GetString("Command_DisplayName_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nach unten.
        /// </summary>
        public static string Command_DisplayName_Down {
            get {
                return ResourceManager.GetString("Command_DisplayName_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editieren.
        /// </summary>
        public static string Command_DisplayName_Edit {
            get {
                return ResourceManager.GetString("Command_DisplayName_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nächste Seite.
        /// </summary>
        public static string Command_DisplayName_Next_Page {
            get {
                return ResourceManager.GetString("Command_DisplayName_Next_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorherige Seite.
        /// </summary>
        public static string Command_DisplayName_Previous_Page {
            get {
                return ResourceManager.GetString("Command_DisplayName_Previous_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drucken.
        /// </summary>
        public static string Command_DisplayName_Print {
            get {
                return ResourceManager.GetString("Command_DisplayName_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string Command_DisplayName_SaveOrUpdate {
            get {
                return ResourceManager.GetString("Command_DisplayName_SaveOrUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchen.
        /// </summary>
        public static string Command_DisplayName_Search {
            get {
                return ResourceManager.GetString("Command_DisplayName_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nach oben.
        /// </summary>
        public static string Command_DisplayName_Up {
            get {
                return ResourceManager.GetString("Command_DisplayName_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EpAccounting.db.
        /// </summary>
        public static string Database_NameWithExtension {
            get {
                return ResourceManager.GetString("Database_NameWithExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Rechnung wurde erfolgreich erstellt..
        /// </summary>
        public static string Dialog_Message_Bill_Created {
            get {
                return ResourceManager.GetString("Dialog_Message_Bill_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Kunde muss mindestens einen Nachnamen und eine Postleitzahl besitzen..
        /// </summary>
        public static string Dialog_Message_ClientHasMissingValues {
            get {
                return ResourceManager.GetString("Dialog_Message_ClientHasMissingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jede Artikelnummer darf nur 1 mal vorkommen..
        /// </summary>
        public static string Dialog_Message_MultipleEqualArticleNumbers {
            get {
                return ResourceManager.GetString("Dialog_Message_MultipleEqualArticleNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein ähnlicher Kunde existiert bereits:
        ///
        ///{0}
        ///
        ///Wollen Sie den Kunden trotzdem speichern?.
        /// </summary>
        public static string Dialog_Question_AddToExistingClient {
            get {
                return ResourceManager.GetString("Dialog_Question_AddToExistingClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll die Rechnung wirklich gelöscht werden?.
        /// </summary>
        public static string Dialog_Question_DeleteBill {
            get {
                return ResourceManager.GetString("Dialog_Question_DeleteBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll der Kunde wirklich gelöscht werden?.
        /// </summary>
        public static string Dialog_Question_DeleteClient {
            get {
                return ResourceManager.GetString("Dialog_Question_DeleteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll die Datenbank überschrieben werden?
        ///
        ///{0}.
        /// </summary>
        public static string Dialog_Question_ShouldOverwriteDatabase {
            get {
                return ResourceManager.GetString("Dialog_Question_ShouldOverwriteDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achtung!.
        /// </summary>
        public static string Dialog_Title_Attention {
            get {
                return ResourceManager.GetString("Dialog_Title_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnung erstellt.
        /// </summary>
        public static string Dialog_Title_Bill_Created {
            get {
                return ResourceManager.GetString("Dialog_Title_Bill_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Rechnung konnte nicht gelöscht werden!.
        /// </summary>
        public static string Dialog_Title_CanNotDeleteBill {
            get {
                return ResourceManager.GetString("Dialog_Title_CanNotDeleteBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Kunde konnte nicht gelöscht werden!.
        /// </summary>
        public static string Dialog_Title_CanNotDeleteClient {
            get {
                return ResourceManager.GetString("Dialog_Title_CanNotDeleteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Rechnung konnte nicht gespeichert werden!.
        /// </summary>
        public static string Dialog_Title_CanNotSaveOrUpdateBill {
            get {
                return ResourceManager.GetString("Dialog_Title_CanNotSaveOrUpdateBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Kunde konnte nicht gespeichert werden!.
        /// </summary>
        public static string Dialog_Title_CanNotSaveOrUpdateClient {
            get {
                return ResourceManager.GetString("Dialog_Title_CanNotSaveOrUpdateClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Kunde existiert bereits!.
        /// </summary>
        public static string Dialog_Title_ClientExistsAlready {
            get {
                return ResourceManager.GetString("Dialog_Title_ClientExistsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datenbank existiert bereits in diesem Ordner!.
        /// </summary>
        public static string Dialog_Title_DatabaseAlreadyExists {
            get {
                return ResourceManager.GetString("Dialog_Title_DatabaseAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datenbank konnte nicht erstellt werden!.
        /// </summary>
        public static string Exception_Message_CouldNotCreateDatabase {
            get {
                return ResourceManager.GetString("Exception_Message_CouldNotCreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datenbank konnte nicht geladen werden!.
        /// </summary>
        public static string Exception_Message_CouldNotLoadDatabase {
            get {
                return ResourceManager.GetString("Exception_Message_CouldNotLoadDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine weiteren Elemente gespeichert..
        /// </summary>
        public static string Exception_Message_EmptyStack {
            get {
                return ResourceManager.GetString("Exception_Message_EmptyStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde kein Pfad für den Rechnungsordner angegeben..
        /// </summary>
        public static string Exception_Message_NoPathToBillFolder {
            get {
                return ResourceManager.GetString("Exception_Message_NoPathToBillFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde kein Pfad zur Rechnungsvorlage angegeben..
        /// </summary>
        public static string Exception_Message_NoPathToBillTemplate {
            get {
                return ResourceManager.GetString("Exception_Message_NoPathToBillTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon_ep_logo {
            get {
                object obj = ResourceManager.GetObject("icon_ep_logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_add {
            get {
                object obj = ResourceManager.GetObject("img_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_arrow_down {
            get {
                object obj = ResourceManager.GetObject("img_arrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_arrow_left {
            get {
                object obj = ResourceManager.GetObject("img_arrow_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_arrow_right {
            get {
                object obj = ResourceManager.GetObject("img_arrow_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_arrow_up {
            get {
                object obj = ResourceManager.GetObject("img_arrow_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_articles {
            get {
                object obj = ResourceManager.GetObject("img_articles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_bills {
            get {
                object obj = ResourceManager.GetObject("img_bills", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_cancel {
            get {
                object obj = ResourceManager.GetObject("img_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_client_add {
            get {
                object obj = ResourceManager.GetObject("img_client_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_client_cancel {
            get {
                object obj = ResourceManager.GetObject("img_client_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_client_edit {
            get {
                object obj = ResourceManager.GetObject("img_client_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_client_saveOrUpdate {
            get {
                object obj = ResourceManager.GetObject("img_client_saveOrUpdate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_client_search {
            get {
                object obj = ResourceManager.GetObject("img_client_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_clients {
            get {
                object obj = ResourceManager.GetObject("img_clients", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_createWord {
            get {
                object obj = ResourceManager.GetObject("img_createWord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_db_connected {
            get {
                object obj = ResourceManager.GetObject("img_db_connected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_db_disconnected {
            get {
                object obj = ResourceManager.GetObject("img_db_disconnected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_delete {
            get {
                object obj = ResourceManager.GetObject("img_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_edit {
            get {
                object obj = ResourceManager.GetObject("img_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_notPrinted {
            get {
                object obj = ResourceManager.GetObject("img_notPrinted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_options {
            get {
                object obj = ResourceManager.GetObject("img_options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_print {
            get {
                object obj = ResourceManager.GetObject("img_print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_printed {
            get {
                object obj = ResourceManager.GetObject("img_printed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_remove {
            get {
                object obj = ResourceManager.GetObject("img_remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_saveOrUpdate {
            get {
                object obj = ResourceManager.GetObject("img_saveOrUpdate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_search {
            get {
                object obj = ResourceManager.GetObject("img_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_BillSearchCriteriaForBillSearchVM.
        /// </summary>
        public static string Message_BillSearchCriteriaForBillSearchVM {
            get {
                return ResourceManager.GetString("Message_BillSearchCriteriaForBillSearchVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_ChangeToBillWorkspaceForMainVM.
        /// </summary>
        public static string Message_ChangeToBillWorkspaceForMainVM {
            get {
                return ResourceManager.GetString("Message_ChangeToBillWorkspaceForMainVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_ClientSearchCriteriaForClientSearchVM.
        /// </summary>
        public static string Message_ClientSearchCriteriaForClientSearchVM {
            get {
                return ResourceManager.GetString("Message_ClientSearchCriteriaForClientSearchVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_CreateNewBillForBillEditVM.
        /// </summary>
        public static string Message_CreateNewBillForBillEditVM {
            get {
                return ResourceManager.GetString("Message_CreateNewBillForBillEditVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_EnableStateForBillItemEditVM.
        /// </summary>
        public static string Message_EnableStateForBillItemEditVM {
            get {
                return ResourceManager.GetString("Message_EnableStateForBillItemEditVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_EnableStateForClientSearchVM.
        /// </summary>
        public static string Message_EnableStateForClientSearchVM {
            get {
                return ResourceManager.GetString("Message_EnableStateForClientSearchVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_FocusArticleForArticlesOptionView.
        /// </summary>
        public static string Message_FocusArticleForArticlesOptionView {
            get {
                return ResourceManager.GetString("Message_FocusArticleForArticlesOptionView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_FocusBillItemsMessageForBillItemEditView.
        /// </summary>
        public static string Message_FocusBillItemsMessageForBillItemEditView {
            get {
                return ResourceManager.GetString("Message_FocusBillItemsMessageForBillItemEditView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_LoadBillItemEditViewModelForBillVM.
        /// </summary>
        public static string Message_LoadBillItemEditViewModelForBillVM {
            get {
                return ResourceManager.GetString("Message_LoadBillItemEditViewModelForBillVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_LoadBillSearchViewModelMessageForBillVM.
        /// </summary>
        public static string Message_LoadBillSearchViewModelMessageForBillVM {
            get {
                return ResourceManager.GetString("Message_LoadBillSearchViewModelMessageForBillVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_LoadBillsFromClientForBillSearchVM.
        /// </summary>
        public static string Message_LoadBillsFromClientForBillSearchVM {
            get {
                return ResourceManager.GetString("Message_LoadBillsFromClientForBillSearchVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_LoadClientForClientEditVM.
        /// </summary>
        public static string Message_LoadClientForClientEditVM {
            get {
                return ResourceManager.GetString("Message_LoadClientForClientEditVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_LoadSelectedBillForBillEditVM.
        /// </summary>
        public static string Message_LoadSelectedBillForBillEditVM {
            get {
                return ResourceManager.GetString("Message_LoadSelectedBillForBillEditVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_OnVatChangeRecalculatePricesForBillItemEditVM.
        /// </summary>
        public static string Message_OnVatChangeRecalculatePricesForBillItemEditVM {
            get {
                return ResourceManager.GetString("Message_OnVatChangeRecalculatePricesForBillItemEditVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_ReloadBillBecauseOfPrintedStateChangeForBillDetailVM.
        /// </summary>
        public static string Message_ReloadBillBecauseOfPrintedStateChangeForBillDetailVM {
            get {
                return ResourceManager.GetString("Message_ReloadBillBecauseOfPrintedStateChangeForBillDetailVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_RemoveBillForBillSearchVM.
        /// </summary>
        public static string Message_RemoveBillForBillSearchVM {
            get {
                return ResourceManager.GetString("Message_RemoveBillForBillSearchVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_RemoveClientForBillEditVM.
        /// </summary>
        public static string Message_RemoveClientForBillEditVM {
            get {
                return ResourceManager.GetString("Message_RemoveClientForBillEditVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_RemoveClientForBillItemEditVM.
        /// </summary>
        public static string Message_RemoveClientForBillItemEditVM {
            get {
                return ResourceManager.GetString("Message_RemoveClientForBillItemEditVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_RemoveClientForBillSearchVM.
        /// </summary>
        public static string Message_RemoveClientForBillSearchVM {
            get {
                return ResourceManager.GetString("Message_RemoveClientForBillSearchVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_RemoveClientForClientSearchVM.
        /// </summary>
        public static string Message_RemoveClientForClientSearchVM {
            get {
                return ResourceManager.GetString("Message_RemoveClientForClientSearchVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_ResetBillItemEditVMAndChangeToSearchWorkspaceForBillVM.
        /// </summary>
        public static string Message_ResetBillItemEditVMAndChangeToSearchWorkspaceForBillVM {
            get {
                return ResourceManager.GetString("Message_ResetBillItemEditVMAndChangeToSearchWorkspaceForBillVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_SwitchToSearchModeAndLoadClientDataForBillEditVM.
        /// </summary>
        public static string Message_SwitchToSearchModeAndLoadClientDataForBillEditVM {
            get {
                return ResourceManager.GetString("Message_SwitchToSearchModeAndLoadClientDataForBillEditVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_UpdateBillValuesMessageForBillSearchVM.
        /// </summary>
        public static string Message_UpdateBillValuesMessageForBillSearchVM {
            get {
                return ResourceManager.GetString("Message_UpdateBillValuesMessageForBillSearchVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_UpdateClientForClientEditVM.
        /// </summary>
        public static string Message_UpdateClientForClientEditVM {
            get {
                return ResourceManager.GetString("Message_UpdateClientForClientEditVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_UpdateClientValuesForBillEditVM.
        /// </summary>
        public static string Message_UpdateClientValuesForBillEditVM {
            get {
                return ResourceManager.GetString("Message_UpdateClientValuesForBillEditVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_UpdateClientValuesForBillSearchVM.
        /// </summary>
        public static string Message_UpdateClientValuesForBillSearchVM {
            get {
                return ResourceManager.GetString("Message_UpdateClientValuesForBillSearchVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_UpdateClientValuesForClientSearchVM.
        /// </summary>
        public static string Message_UpdateClientValuesForClientSearchVM {
            get {
                return ResourceManager.GetString("Message_UpdateClientValuesForClientSearchVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_UpdateConnectionStateForMainVM.
        /// </summary>
        public static string Message_UpdateConnectionStateForMainVM {
            get {
                return ResourceManager.GetString("Message_UpdateConnectionStateForMainVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_OnVatChangeRecalculatePricesForBillItemEditVM.
        /// </summary>
        public static string Message_UpdateSumsForBillItemEditVM {
            get {
                return ResourceManager.GetString("Message_UpdateSumsForBillItemEditVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_WorkspaceEnableStateForMainVM.
        /// </summary>
        public static string Message_WorkspaceEnableStateForMainVM {
            get {
                return ResourceManager.GetString("Message_WorkspaceEnableStateForMainVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Clients&gt;
        ///  &lt;Client ClientID=&quot;1&quot; Title=&quot;Herr&quot; FirstName=&quot;Andre&quot; LastName=&quot;Multerer&quot; Street=&quot;Benzstraße&quot; HouseNumber=&quot;1a&quot;
        ///          PostalCode=&quot;93053&quot; City=&quot;Regensburg&quot; DateOfBirth=&quot;06.11.1993&quot; PhoneNumber1=&quot;09942/902097&quot;
        ///          PhoneNumber2=&quot;09942/902099&quot; MobileNumber=&quot;+49 160 55-07-869&quot; Telefax=&quot;09942/902098&quot;
        ///          Email=&quot;andre.multerer@gmail.com&quot;&gt;
        ///    &lt;Bill BillID=&quot;1&quot; Printed=&quot;false&quot; Date=&quot;27.11.2016&quot; KindOfBill=&quot;Rechnung&quot; KindOfVAT=&quot;inkl_MwSt&quot; VatPercen [rest of string was truncated]&quot;;.
        /// </summary>
        public static string testdata {
            get {
                return ResourceManager.GetString("testdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie ein gültiges Datum ein..
        /// </summary>
        public static string ValidationError_InvalidDate {
            get {
                return ResourceManager.GetString("ValidationError_InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikel.
        /// </summary>
        public static string Workspace_Title_Articles {
            get {
                return ResourceManager.GetString("Workspace_Title_Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnungen.
        /// </summary>
        public static string Workspace_Title_Bills {
            get {
                return ResourceManager.GetString("Workspace_Title_Bills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunden.
        /// </summary>
        public static string Workspace_Title_Clients {
            get {
                return ResourceManager.GetString("Workspace_Title_Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionen.
        /// </summary>
        public static string Workspace_Title_Options {
            get {
                return ResourceManager.GetString("Workspace_Title_Options", resourceCulture);
            }
        }
    }
}
