//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpAccounting.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EpAccounting.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Command_DisplayName_Add {
            get {
                return ResourceManager.GetString("Command_DisplayName_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Command_DisplayName_Cancel {
            get {
                return ResourceManager.GetString("Command_DisplayName_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Command_DisplayName_Delete {
            get {
                return ResourceManager.GetString("Command_DisplayName_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string Command_DisplayName_Down {
            get {
                return ResourceManager.GetString("Command_DisplayName_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Command_DisplayName_Edit {
            get {
                return ResourceManager.GetString("Command_DisplayName_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        public static string Command_DisplayName_Next_Page {
            get {
                return ResourceManager.GetString("Command_DisplayName_Next_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page.
        /// </summary>
        public static string Command_DisplayName_Previous_Page {
            get {
                return ResourceManager.GetString("Command_DisplayName_Previous_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveOrUpdate.
        /// </summary>
        public static string Command_DisplayName_SaveOrUpdate {
            get {
                return ResourceManager.GetString("Command_DisplayName_SaveOrUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Command_DisplayName_Search {
            get {
                return ResourceManager.GetString("Command_DisplayName_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string Command_DisplayName_Up {
            get {
                return ResourceManager.GetString("Command_DisplayName_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN_Bill_Cancel.
        /// </summary>
        public static string Command_Message_Bill_Cancel {
            get {
                return ResourceManager.GetString("Command_Message_Bill_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN_Bill_Delete.
        /// </summary>
        public static string Command_Message_Bill_Delete {
            get {
                return ResourceManager.GetString("Command_Message_Bill_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN_Bill_Edit.
        /// </summary>
        public static string Command_Message_Bill_Edit {
            get {
                return ResourceManager.GetString("Command_Message_Bill_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN_Bill_SaveOrUpdate.
        /// </summary>
        public static string Command_Message_Bill_SaveOrUpdate {
            get {
                return ResourceManager.GetString("Command_Message_Bill_SaveOrUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN_Bill_Search.
        /// </summary>
        public static string Command_Message_Bill_Search {
            get {
                return ResourceManager.GetString("Command_Message_Bill_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN_BillItem_Add.
        /// </summary>
        public static string Command_Message_BillItem_Add {
            get {
                return ResourceManager.GetString("Command_Message_BillItem_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN_BillItem_Delete.
        /// </summary>
        public static string Command_Message_BillItem_Delete {
            get {
                return ResourceManager.GetString("Command_Message_BillItem_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN_BillItem_Down.
        /// </summary>
        public static string Command_Message_BillItem_Down {
            get {
                return ResourceManager.GetString("Command_Message_BillItem_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN_BillItem_Up.
        /// </summary>
        public static string Command_Message_BillItem_Up {
            get {
                return ResourceManager.GetString("Command_Message_BillItem_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN_Client_Add.
        /// </summary>
        public static string Command_Message_Client_Add {
            get {
                return ResourceManager.GetString("Command_Message_Client_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN_Client_Cancel.
        /// </summary>
        public static string Command_Message_Client_Cancel {
            get {
                return ResourceManager.GetString("Command_Message_Client_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN_Client_Delete.
        /// </summary>
        public static string Command_Message_Client_Delete {
            get {
                return ResourceManager.GetString("Command_Message_Client_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN_Client_Edit.
        /// </summary>
        public static string Command_Message_Client_Edit {
            get {
                return ResourceManager.GetString("Command_Message_Client_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN_Client_Load.
        /// </summary>
        public static string Command_Message_Client_Load {
            get {
                return ResourceManager.GetString("Command_Message_Client_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN_Client_SaveOrUpdate.
        /// </summary>
        public static string Command_Message_Client_SaveOrUpdate {
            get {
                return ResourceManager.GetString("Command_Message_Client_SaveOrUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN_Client_Search.
        /// </summary>
        public static string Command_Message_Client_Search {
            get {
                return ResourceManager.GetString("Command_Message_Client_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN_Next_Page.
        /// </summary>
        public static string Command_Message_Next_Page {
            get {
                return ResourceManager.GetString("Command_Message_Next_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN_Previous_Page.
        /// </summary>
        public static string Command_Message_Previous_Page {
            get {
                return ResourceManager.GetString("Command_Message_Previous_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnungsprogramm.db.
        /// </summary>
        public static string Database_NameWithExtension {
            get {
                return ResourceManager.GetString("Database_NameWithExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Kunde muss mindestens einen Vor- und Nachnamen besitzen..
        /// </summary>
        public static string Dialog_Message_ClientHasMissingNamePart {
            get {
                return ResourceManager.GetString("Dialog_Message_ClientHasMissingNamePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein ähnlicher Kunde existiert bereits:
        ///
        ///{0}
        ///
        ///Wollen Sie den Kunden trotzdem speichern?.
        /// </summary>
        public static string Dialog_Question_AddToExistingClient {
            get {
                return ResourceManager.GetString("Dialog_Question_AddToExistingClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll die Rechnung wirklich gelöscht werden?.
        /// </summary>
        public static string Dialog_Question_DeleteBill {
            get {
                return ResourceManager.GetString("Dialog_Question_DeleteBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll der Kunde wirklich gelöscht werden?.
        /// </summary>
        public static string Dialog_Question_DeleteClient {
            get {
                return ResourceManager.GetString("Dialog_Question_DeleteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll die Datenbank überschrieben werden?
        ///
        ///{0}.
        /// </summary>
        public static string Dialog_Question_ShouldOverwriteDatabase {
            get {
                return ResourceManager.GetString("Dialog_Question_ShouldOverwriteDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achtung!.
        /// </summary>
        public static string Dialog_Title_Attention {
            get {
                return ResourceManager.GetString("Dialog_Title_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Rechnung konnte nicht gelöscht werden!.
        /// </summary>
        public static string Dialog_Title_CanNotDeleteBill {
            get {
                return ResourceManager.GetString("Dialog_Title_CanNotDeleteBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Kunde konnte nicht gelöscht werden!.
        /// </summary>
        public static string Dialog_Title_CanNotDeleteClient {
            get {
                return ResourceManager.GetString("Dialog_Title_CanNotDeleteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Rechnung konnte nicht gespeichert werden!.
        /// </summary>
        public static string Dialog_Title_CanNotSaveOrUpdateBill {
            get {
                return ResourceManager.GetString("Dialog_Title_CanNotSaveOrUpdateBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Kunde konnte nicht gespeichert werden!.
        /// </summary>
        public static string Dialog_Title_CanNotSaveOrUpdateClient {
            get {
                return ResourceManager.GetString("Dialog_Title_CanNotSaveOrUpdateClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Kunde existiert bereits!.
        /// </summary>
        public static string Dialog_Title_ClientExistsAlready {
            get {
                return ResourceManager.GetString("Dialog_Title_ClientExistsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datenbank existiert bereits in diesem Ordner!.
        /// </summary>
        public static string Dialog_Title_DatabaseAlreadyExists {
            get {
                return ResourceManager.GetString("Dialog_Title_DatabaseAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datenbank konnte nicht erstellt werden!.
        /// </summary>
        public static string Exception_Message_CouldNotCreateDatabase {
            get {
                return ResourceManager.GetString("Exception_Message_CouldNotCreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datenbank konnte nicht geladen werden!.
        /// </summary>
        public static string Exception_Message_CouldNotLoadDatabase {
            get {
                return ResourceManager.GetString("Exception_Message_CouldNotLoadDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine weiteren Elemente gespeichert..
        /// </summary>
        public static string Exception_Message_EmptyStack {
            get {
                return ResourceManager.GetString("Exception_Message_EmptyStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon_ep_logo {
            get {
                object obj = ResourceManager.GetObject("icon_ep_logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_add {
            get {
                object obj = ResourceManager.GetObject("img_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_arrow_down {
            get {
                object obj = ResourceManager.GetObject("img_arrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_arrow_left {
            get {
                object obj = ResourceManager.GetObject("img_arrow_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_arrow_right {
            get {
                object obj = ResourceManager.GetObject("img_arrow_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_arrow_up {
            get {
                object obj = ResourceManager.GetObject("img_arrow_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_bills {
            get {
                object obj = ResourceManager.GetObject("img_bills", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_cancel {
            get {
                object obj = ResourceManager.GetObject("img_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_client_add {
            get {
                object obj = ResourceManager.GetObject("img_client_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_client_cancel {
            get {
                object obj = ResourceManager.GetObject("img_client_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_client_edit {
            get {
                object obj = ResourceManager.GetObject("img_client_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_client_saveOrUpdate {
            get {
                object obj = ResourceManager.GetObject("img_client_saveOrUpdate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_client_search {
            get {
                object obj = ResourceManager.GetObject("img_client_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_clients {
            get {
                object obj = ResourceManager.GetObject("img_clients", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_db_connected {
            get {
                object obj = ResourceManager.GetObject("img_db_connected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_db_disconnected {
            get {
                object obj = ResourceManager.GetObject("img_db_disconnected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_delete {
            get {
                object obj = ResourceManager.GetObject("img_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_edit {
            get {
                object obj = ResourceManager.GetObject("img_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_options {
            get {
                object obj = ResourceManager.GetObject("img_options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_remove {
            get {
                object obj = ResourceManager.GetObject("img_remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_saveOrUpdate {
            get {
                object obj = ResourceManager.GetObject("img_saveOrUpdate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_search {
            get {
                object obj = ResourceManager.GetObject("img_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_BillSearchCriteriaForBillSearchVM.
        /// </summary>
        public static string Messenger_Message_BillSearchCriteriaForBillSearchVM {
            get {
                return ResourceManager.GetString("Messenger_Message_BillSearchCriteriaForBillSearchVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_ClientSearchCriteriaForClientSearchVM.
        /// </summary>
        public static string Messenger_Message_ClientSearchCriteriaForClientSearchVM {
            get {
                return ResourceManager.GetString("Messenger_Message_ClientSearchCriteriaForClientSearchVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_CreateNewBillMessageForBillEditVM.
        /// </summary>
        public static string Messenger_Message_CreateNewBillMessageForBillEditVM {
            get {
                return ResourceManager.GetString("Messenger_Message_CreateNewBillMessageForBillEditVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_CreateNewBillMessageForMainVM.
        /// </summary>
        public static string Messenger_Message_CreateNewBillMessageForMainVM {
            get {
                return ResourceManager.GetString("Messenger_Message_CreateNewBillMessageForMainVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_EnableStateMessageForBillItemEditVM.
        /// </summary>
        public static string Messenger_Message_EnableStateMessageForBillItemEditVM {
            get {
                return ResourceManager.GetString("Messenger_Message_EnableStateMessageForBillItemEditVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_EnableStateMessageForClientSearchVM.
        /// </summary>
        public static string Messenger_Message_EnableStateMessageForClientSearchVM {
            get {
                return ResourceManager.GetString("Messenger_Message_EnableStateMessageForClientSearchVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_FocusBillItemsMessageForBillItemEditView.
        /// </summary>
        public static string Messenger_Message_FocusBillItemsMessageForBillItemEditView {
            get {
                return ResourceManager.GetString("Messenger_Message_FocusBillItemsMessageForBillItemEditView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_LoadBillItemEditViewModelMessageForBillVM.
        /// </summary>
        public static string Messenger_Message_LoadBillItemEditViewModelMessageForBillVM {
            get {
                return ResourceManager.GetString("Messenger_Message_LoadBillItemEditViewModelMessageForBillVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_LoadBillSearchViewModelMessageForBillVM.
        /// </summary>
        public static string Messenger_Message_LoadBillSearchViewModelMessageForBillVM {
            get {
                return ResourceManager.GetString("Messenger_Message_LoadBillSearchViewModelMessageForBillVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_LoadSelectedBillForBillEditVM.
        /// </summary>
        public static string Messenger_Message_LoadSelectedBillForBillEditVM {
            get {
                return ResourceManager.GetString("Messenger_Message_LoadSelectedBillForBillEditVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_LoadSelectedClientMessageForClientEditVM.
        /// </summary>
        public static string Messenger_Message_LoadSelectedClientMessageForClientEditVM {
            get {
                return ResourceManager.GetString("Messenger_Message_LoadSelectedClientMessageForClientEditVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_RemoveBillMessageForBillSearchVM.
        /// </summary>
        public static string Messenger_Message_RemoveBillMessageForBillSearchVM {
            get {
                return ResourceManager.GetString("Messenger_Message_RemoveBillMessageForBillSearchVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_RemoveBillMessageForBillVM.
        /// </summary>
        public static string Messenger_Message_RemoveBillMessageForBillVM {
            get {
                return ResourceManager.GetString("Messenger_Message_RemoveBillMessageForBillVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_RemoveClientMessageForClientSearchVM.
        /// </summary>
        public static string Messenger_Message_RemoveClientMessageForClientSearchVM {
            get {
                return ResourceManager.GetString("Messenger_Message_RemoveClientMessageForClientSearchVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_UpdateBillValues.
        /// </summary>
        public static string Messenger_Message_UpdateBillValuesMessageForBillSearchVM {
            get {
                return ResourceManager.GetString("Messenger_Message_UpdateBillValuesMessageForBillSearchVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_UpdateClientValuesMessageForBillEditVM.
        /// </summary>
        public static string Messenger_Message_UpdateClientValuesMessageForBillEditVM {
            get {
                return ResourceManager.GetString("Messenger_Message_UpdateClientValuesMessageForBillEditVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_UpdateClinetValuesMessageForBillSearchVM.
        /// </summary>
        public static string Messenger_Message_UpdateClientValuesMessageForBillSearchVM {
            get {
                return ResourceManager.GetString("Messenger_Message_UpdateClientValuesMessageForBillSearchVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_UpdateClientValuesMessageForClientSearchVM.
        /// </summary>
        public static string Messenger_Message_UpdateClientValuesMessageForClientSearchVM {
            get {
                return ResourceManager.GetString("Messenger_Message_UpdateClientValuesMessageForClientSearchVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_UpdateConnectionStateMessageForMainVM.
        /// </summary>
        public static string Messenger_Message_UpdateConnectionStateMessageForMainVM {
            get {
                return ResourceManager.GetString("Messenger_Message_UpdateConnectionStateMessageForMainVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Clients&gt;
        ///  &lt;Client ClientID=&quot;1&quot; Title=&quot;Herr&quot; FirstName=&quot;Andre&quot; LastName=&quot;Multerer&quot; Street=&quot;Benzstraße&quot; HouseNumber=&quot;1a&quot;
        ///          PostalCode=&quot;93053&quot; City=&quot;Regensburg&quot; DateOfBirth=&quot;06.11.1993&quot; PhoneNumber1=&quot;09942/902097&quot;
        ///          PhoneNumber2=&quot;09942/902099&quot; MobileNumber=&quot;+49 160 55-07-869&quot; Telefax=&quot;09942/902098&quot;
        ///          Email=&quot;andre.multerer@gmail.com&quot;&gt;
        ///    &lt;Bill BillID=&quot;1&quot; Date=&quot;27.11.2016&quot; KindOfBill=&quot;Rechnung&quot; KindOfVAT=&quot;inkl. MwSt&quot; VATPercentage=&quot;19&quot;&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TestData {
            get {
                return ResourceManager.GetString("TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikel.
        /// </summary>
        public static string Workspace_Title_Articles {
            get {
                return ResourceManager.GetString("Workspace_Title_Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnungen.
        /// </summary>
        public static string Workspace_Title_Bills {
            get {
                return ResourceManager.GetString("Workspace_Title_Bills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunden.
        /// </summary>
        public static string Workspace_Title_Clients {
            get {
                return ResourceManager.GetString("Workspace_Title_Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionen.
        /// </summary>
        public static string Workspace_Title_Options {
            get {
                return ResourceManager.GetString("Workspace_Title_Options", resourceCulture);
            }
        }
    }
}
